pr1
T-V-N/gophkeeper pull request #1
Opened 2023-05-13 09:18 UTC by T-V-N

2023-05-17 16:04 UTC, rktkov requested changes

2023-05-17 16:04 UTC, rktkov commented on internal/utils/router.go
> +package utils
Кода нет, файл не нужен. Как только решишь добавить используемый код, тогда и добавляй файл.

2023-05-17 16:04 UTC, rktkov commented on internal/storage/user.go
> +func InitUser(conn *pgxpool.Pool) (*UserStorage, error) {
Название InitUserStorage выглядит более понятным.

2023-05-17 16:04 UTC, rktkov commented on internal/storage/user.go
> +type User struct {
Стоит вынести в отдельный пакет с моделями. И так сделать со всеми структурами, определяющими сущности.

2023-05-17 16:04 UTC, rktkov commented on internal/storage/s3/s3.go
> +	"github.com/T-V-N/gophkeeper/internal/config"
Стоит разделять на 3 блока (системный пакет, внешние, внутренние). Проверь, пожалуйста, во всем коде.

2023-05-17 16:04 UTC, rktkov commented on internal/config/config.go
> +	S3URL                string `env:"S3URL"`
Стоит настройки специфические для конкретного элемента системы собрать в отдельной конфигурационной структуре - S3Config, AppConfig и т.д. И потом вложить их в общую структуру конфига.

2023-05-17 16:04 UTC, rktkov commented on internal/app/user.go
> +	user, err := storage.InitUser(conn)
Сюда можно передавать конфигурацию и инициализировать подключение уже внутри хранилища. Таким образом, можно исключить зависимость этого уровня от конкретики реализации хранилища.

2023-05-17 16:04 UTC, rktkov commented on internal/app/user.go
> +	"go.uber.org/zap"
Стоит сделать внутренний пакет лог и внутри него спрятать детали использования внешнего модуля логирования.

2023-05-17 16:04 UTC, rktkov commented on internal/helpers/emailSender.go
> +	address := "test@truepnl.com"
Вот это явно надо убирать, как минимум в настройки приложения и не хард-кодить.

2023-05-17 16:04 UTC, rktkov commented on internal/helpers/emailSender.go
> +	m.SetTemplateID("d-99f48121d63f4e58b67098dd063bc82d")
Туда же, в настройки.

2023-05-22 23:42 UTC, T-V-N commented on internal/storage/user.go
> +type User struct {
вот тут не понял
модели же вроде определены внутри пакета storage как раз в рамках этих структур?

2023-05-25 06:43 UTC, rktkov approved these changes
Принят с косметическими комментариями.

2023-05-25 06:43 UTC, rktkov commented on internal/storage/password.go
> +	if err != nil {
Лишние блоки проверки на ошибку. Хватит одного.

2023-05-25 06:43 UTC, rktkov commented on internal/storage/password.go
> +	if err != nil {
Лишний блок проверки на ошибку.

2023-05-25 06:43 UTC, rktkov commented on internal/storage/file.go
> +	if err != nil {
Лишний блок проверки на ошибку. Стоит все такие части кода изменить.

2023-05-25 12:29 UTC, merged